Algoritmo "Mod 11 = 5"
// Lógica de Programação Orientada a Objeto
// Aldo Henrique

Var
a: inteiro
init: caractere

Inicio
escreval("Divisão por 11 com resto 5. Pressione Enter para começar.")
leia(init)
limpatela
escreval("Os números que quando divididos por 11")
escreval("deixam resto 5, são:")
para a de 1000 até 1999 faça
   se(a mod 11 = 5)então
      escreva(a)
   fimse
fimpara

Fimalgoritmo
